### ISSUE TITLE
404s are sent as errors to Honeybadger

### ISSUE THREAD

**Issue by maxim** [honeybadger-io/honeybadger-elixir#130] opened 2018-02-18 19:48 UTC
I am using v0.8.0. For some reason we're getting 404s reported as errors.

```
❯ curl -I [redacted-url-that-produces-404]
HTTP/1.1 404 Not Found
[…]
```

The error is coming from Ecto query not finding a thing, but perhaps Honeybadger is failing to match [something here](https://github.com/honeybadger-io/honeybadger-elixir/blob/ee3417585b83d93266b4986084d048a76f13d007/lib/honeybadger/plug.ex#L58) (didn't research this, just guessing from a glance at the code).

We aren't doing anything weird, just have `use Honeybadger.Plug` in the router.

Phoenix 1.3.0, Elixir 1.6.0, Erlang 20

**Comment by minhajuddin** [comment] 2018-02-20 11:35
Thanks for reporting this, I'll take a look at it shortly.

**Comment by minhajuddin** [comment] 2018-02-27 14:16
This is a regression, will fix it soon.

**Comment by sorentwo** [comment] 2018-02-27 15:08
@minhajuddin This one is on me, I'm happy to submit a fix. Did you replicate it with crywolf?

**Comment by minhajuddin** [comment] 2018-02-27 15:46
@sorentwo Yes, this is happening when `Repo.get!(User, 1)` returns a not found error.

**Comment by minhajuddin** [comment] 2018-03-06 03:42
@maxim This issue should be fixed now, can you try this in your app using `github: honeybadger-io/honeybadger-elixir` in your mix.exs

**Comment by maxim** [comment] 2018-03-12 15:12
@minhajuddin Gave it some production time, seems good. 👍

**Comment by robinvdvleuten** [comment] 2018-12-11 08:44
I still have 404 errors logged by Honeybadger;

```
Erlang error: {{%Phoenix.Router.NoRouteError{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}
```

**Comment by minhajuddin** [comment] 2018-12-17 17:37
@robinvdvleuten, @fabiokr Can you guys share your honeybadger and phoenix version info. The latest version shouldn't have this issue.

**Comment by fabiokr** [comment] 2018-12-17 18:06
@minhajuddin I am on phoenix 1.4.0 and honeybadger 0.10.3.

**Comment by sorentwo** [comment] 2018-12-17 18:09
My hunch is that this is coming from changes in 1.4.0...

**Comment by robinvdvleuten** [comment] 2018-12-24 12:01
@minhajuddin same here, I am on phoenix 1.4.0 and honeybadger 0.10.3.

**Comment by tielur** [comment] 2019-01-02 23:49
I'm also getting this problem:

honeybadger 0.10.3
phoenix 1.4.0

**Comment by joshuap** [comment] 2019-01-14 17:54
@sorentwo do you have any ideas on this one? I'll reopen the issue until I'm sure this has been fixed (and I'm happy to help out if needed).

**Comment by nurugger07** [comment] 2019-04-04 18:38
@joshuap has this been assigned? I can take a look today.

**Comment by sorentwo** [comment] 2019-04-04 19:06
I'm not sure if this is still an issue. We haven't seen it for a while now since 0.11.

**Comment by joshuap** [comment] 2019-04-04 21:47
I haven't had any reports of this, but nope, it's not currently assigned. If you can reproduce and want to take a stab at it, feel free @nurugger07!

**Comment by nurugger07** [comment] 2019-04-05 03:42
@joshuap yeah #193 is the one that had our attention but then I saw this as well. I can take a look tomorrow and see if we can get these cleared up.

**Comment by sorentwo** [comment] 2019-06-01 22:20
We haven't had any new reports of this since 0.11 was released. I'm going to close this one out.

**Closed by sorentwo** 2019-06-01 22:20 UTC
Labels: bug, in progress
