### ISSUE TITLE
Phoenix.Router.NoRouteError being reported

### ISSUE THREAD

**Issue by sezaru** [honeybadger-io/honeybadger-elixir#335] opened 2021-02-16 03:35 UTC
Hello, 

For some reason, HoneyBadger is sending `Phoenix.Router.NoRouteError` errors even when I inserted my `use Honeybadger.Plug` after the `use CoreWeb, :router` call.

Phoenix version: 1.5.3
Honeybadger version: 0.15

Here is a screenshot of the error in the HoneyBadger dashboard:

![image](https://user-images.githubusercontent.com/279828/108015360-df0cf500-6fee-11eb-8cf4-441301c3c42b.png)

Feel free to ask me for any more information needed.

**Comment by sezaru** [comment] 2021-02-16 03:39
Oh, I just noticed that it seems that HoneyBadger is also accumulating a lot of different errors with that one for some reason:

![image](https://user-images.githubusercontent.com/279828/108015536-37dc8d80-6fef-11eb-8535-542242e5ce01.png)

Seems like that because of that `ErlangError` title, HoneyBadger is thinking every error with this same title is the same error.. If this is another issue let me know and I will create a separate issue for it.

**Comment by TraceyOnim** [comment] 2021-07-21 22:01
@sezaru I have tried reproducing the error with the phoenix and honeybadger version specified. Still, I'm unable to get the bug you are facing. Kindly confirm with me the Elixir and Erlang versions that you are using. 

@joshuap , I have seen that there was a fix for this bug that was released in version 0.11, any ideas on how this might be recurring?

**Comment by joshuap** [comment] 2021-07-22 19:48
> @joshuap , I have seen that there was a fix for this bug that was released in version 0.11, any ideas on this one?

I'm not sure to be honest, but @sorentwo might have input. This issue does look similar to this old one: https://github.com/honeybadger-io/honeybadger-elixir/issues/130

**Comment by sorentwo** [comment] 2021-07-22 20:26
Something in those error messages looks wrong. They're all generic erlang errors stacked three levels deep like they are wrapped. I wouldn't expect the default filter to match on those based on how they're structured, but I admit that I don't know why they're formatted that way.

**Comment by TraceyOnim** [comment] 2021-07-23 07:58
The problem is that on my end everything seems to be working fine, it could be at least easier if we could reproduce the same error. 

I think the formatting was also handled if I'm not wrong .

**Comment by joshuap** [comment] 2021-07-26 17:39
Thanks, everyone. Let's keep this open a while longer to see if anyone can provide additional data to reproduce. I'm fine with closing it in a few weeks, otherwise.

**Closed** 2022-10-27 18:53 UTC
Labels: bug, help wanted
