### ISSUE TITLE
Don't rely on Mix

### ISSUE THREAD

**Issue by smeevil** [honeybadger-io/honeybadger-elixir#8] opened 2015-09-17 14:37 UTC
When running in production i see you are relying on Mix.env but it's ill advised to include Mix as a dependency in production (according to Jose Valim and Chris McCord.

Also when using Exrm to deploy, Mix is not included in the build (unless explicitly added, which you should not:D ). Even if you do include it, Mix.env will return :dev in production.

It would be nice if you could update the dependency and in stead rely on the Application.get_env to get the values your are looking for, which as far as I could find is only getting the running environment (test/dev/prod).

I'm quite new to elixir / phoenix and am not yet sure if Application.get_env is the best way to do this, but as you are using it already extensively throughout the code base, it might be the right place. The only downside would be that you need to add the config to config/test.exs config/dev.exs config/prod.exs ?

An other option could be to set a shell environment value, but that might cause issues again for people using Heroku ?

/Gerard

**Comment by rbishop** [comment] 2015-09-17 14:53
To the best of my knowledge, we only make use of `Mix.env` at compile time so Mix should be available at that point. `notify` is a macro: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger.ex#L105-L128

Has this caused an issue in production or during the release process for you?

**Comment by smeevil** [comment] 2015-09-17 14:54
In production deploying with Exrm : 

Request: GET /error
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: Mix.env/0 (module Mix is not available)
        Mix.env()
        (honeybadger) lib/honeybadger/notice.ex:37: Honeybadger.Notice.server/0
        (honeybadger) lib/honeybadger/notice.ex:24: Honeybadger.Notice.new/3
        (honeybadger) lib/honeybadger.ex:136: Honeybadger.do_notify/3
        (plug) lib/plug/error_handler.ex:94: Plug.ErrorHandler.__catch__/5
        (sheep) lib/sheep/endpoint.ex:1: Sheep.Endpoint.phoenix_pipeline/1
        (sheep) lib/phoenix/endpoint/render_errors.ex:34: Sheep.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4

**Comment by rbishop** [comment] 2015-09-17 15:06
Thanks for the stacktrace! I'll dig into this tonight.

**Comment by smeevil** [comment] 2015-09-17 15:12
I did make a change to the source where I resolve the Mix.env at compile time. If i now remove Mix from the application dependency it works in production. But the error report still has dev as environment. 

I'll add a pull request so you can see the changes

**Comment by rbishop** [comment] 2015-10-14 23:12
This was resolved in e8da6f77

**Comment by joshuap** [comment] 2015-10-21 02:47
I (or actually, @knewter) found another Mix dependency: https://github.com/honeybadger-io/honeybadger-elixir/blob/09e0829e3b1aed16d900734076648d5f0d90f640/lib/honeybadger/notice.ex#L37

This is causing his app to report as "prod" even though he's really compiling with `MIX_ENV=dev`. I wonder if it would make a difference if we set the default environment_name as a config option in [our mix.exs](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/mix.exs#L20)? It would be nice to make environment_name a config option in any case.

**Comment by muhmi** [comment] 2015-10-26 12:52
Please do make `environment_name ` a config option.

First of all after building a release `poison` application is not started with the rest of applications. Missing from mix.exs application list?

Second issue now is that I am still not getting any error messages to honeybadger but also do not see any issue in logs related to this lib :D Need to investigate that :D

**Comment by rbishop** [comment] 2015-10-26 14:20
As far as I know, `Poison` does not have an Application to start. It is just a library.

**Comment by knewter** [comment] 2015-10-26 14:22
Confirmed re poison: https://github.com/devinus/poison/blob/master/mix.exs#L19

**Comment by muhmi** [comment] 2015-10-26 14:51
Hi!

Yes you are correct - should have given more thought before posting :) The issue seems to be that exrm does not bundle it along unless I specifically add it to my applications list. Sorry for being a n00b :)

**Comment by muhmi** [comment] 2015-10-26 15:07
Hmm, I wonder if you still should put poison to your applications list even it is not something that needs to be started. https://hexdocs.pm/exrm/extra-common-issues.html

**Comment by rbishop** [comment] 2015-10-26 16:18
New or not, all feedback is welcome and appreciated so thank you!

Thank you for sharing that link. That's interesting. I'll have to do some testing with exrm to see if it compiles depedencies that aren't specified in `:applications`. I thought that setting only controlled OTP Applications that needed to be `start`ed.

**Comment by muhmi** [comment] 2015-10-26 17:00
Hi,

Yeah - that can get confusing. From the Erlang docs it seems that application can be something that either starts (has a process) or is just a library (application).

"The simplest applications do not have any processes, but consist of a collection of functional modules. Such an application is called a library application. An example of a library application is STDLIB."
http://www.erlang.org/doc/design_principles/des_princ.html

So I guess this goes back to Erlang community having good times with making things confusing? =)

**Comment by joshuap** [comment] 2015-10-26 21:17
@rbishop do we need to worry about the references to `Honeybadger.Mixfile` in [`Honeybadger.Notice`](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/notice.ex#L28)?

**Comment by knewter** [comment] 2015-10-26 21:57
You shouldn't, as that's compile-time

On Mon, Oct 26, 2015 at 4:17 PM, joshuap <notifications@github.com> wrote:

> @rbishop <https://github.com/rbishop> do we need to worry about the
> references to Honeybadger.Mixfile in Honeybadger.Notice
> <https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/notice.ex#L28>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/honeybadger-io/honeybadger-elixir/issues/8#issuecomment-151287428>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by joshuap** [comment] 2015-10-26 22:32
Makes sense. Thanks!

**Closed** 2015-10-26 22:33 UTC

**Comment by rbishop** [comment] 2015-10-27 01:58
That makes me wonder if instead of

```elixir
@mix_env Mix.env
def server do
  %{environment_name: @mix_env}
end
```

we did:

```elixir
mix_env = Mix.env
def server do
  %{environment_name: @mix_env}
end
```

Would we have had those wrong environment compile issues?
