### ISSUE TITLE
Erlang error: :case_clause from Honeybadger

### ISSUE THREAD

**Issue by axelson** [honeybadger-io/honeybadger-elixir#200] opened 2019-02-07 00:54 UTC
Getting this on 0.10.2 and 0.10.3:

Stacktrace:
```
process.ex  662 info/2
lib/process.ex:662:in `info/2'
honeybadger.ex  316 backtrace/1
lib/honeybadger.ex:316:in `backtrace/1'
honeybadger.ex  209 notify/3
lib/honeybadger.ex:209:in `notify/3'
logger.ex  54 handle_error/1
lib/honeybadger/logger.ex:54:in `handle_error/1'
logger.ex  21 handle_event/2
lib/honeybadger/logger.ex:21:in `handle_event/2'
gen_event.erl  577 server_update/4
gen_event.erl:577:in `server_update/4'
gen_event.erl  559 server_notify/4
gen_event.erl:559:in `server_notify/4'
```

Honeybadger link for any employees: https://app.honeybadger.io/projects/50379/faults/39800245#notice-summary

**Comment by joshuap** [comment] 2019-02-07 17:00
Thanks for the report, @axelson. Do you have any code that can reproduce the error, by any chance?

**Comment by axelson** [comment] 2019-02-07 18:59
No I don't sorry. Nothing in the stacktrace is our code so I'm not really sure what's happening.

**Comment by bernardd** [comment] 2019-02-14 23:27
We're seeing the same thing, but we're generally able to extract the correct call stack from our logging system. In our most recent example the code looked like this:

```elixir
  defp send_invitation(
         %{e164_phone_number: number} = r,
         sent_numbers,
         requestor
       )
       when not is_nil(number) do
    r =
      with {:ok, body} <- sms_invitation_body(requestor),
           :ok <- Messenger.send(number, body, requestor) do
        Map.put(r, :result, :external_invitation_sent)
      else
        {:error, e} ->
          r
          |> Map.put(:result, :sms_error)
          |> Map.put(:error, inspect(e))
      end
```

The key bit is the `with` clause - the `Messenger.send` function returned `{:error, "Some string or other", 404}` which matched neither the success case nor the single pattern under `else`, triggering a `with_clause` exception.

We're running erlang 21 (which I just noticed it a couple of minor releases behind - I should fix that) and Elixir 1.7.1. Presuming you can see our account, the error is https://app.honeybadger.io/projects/50679/faults/40249305. Please let me know if I can provide any more info.

**Comment by axelson** [comment] 2019-02-15 00:37
@bernardd thanks for that, your report is much more helpful than mine :)

For reference we're running on Elixir 1.7.4 and Erlang 21.0.4

**Comment by sorentwo** [comment] 2019-02-15 14:43
@bernardd @axelson Thank you for the additional information. I've scheduled time to work on this next week. However, I don't work at Honeybadger and can't see the details of that fault. We get plenty of these types of errors ourselves though, so I should have plenty to work from.

**Comment by sorentwo** [comment] 2019-02-28 19:21
@bernardd @axelson The logger changes have just been released as `0.11.0`, please take a look and report back whether it has improved things for you.

**Comment by sorentwo** [comment] 2019-05-29 14:05
@bernardd @axelson It has been a few months since 0.11 was released. Have things gotten better for you?

**Comment by axelson** [comment] 2019-05-29 18:14
Yeah, this error has disappeared after the update to 0.11 :+1: Thanks!

**Closed** 2019-05-29 18:16 UTC
Labels: bug

**Comment by bernardd** [comment] 2019-05-30 00:20
Yep, same here - all good. Thanks!
