### ISSUE TITLE
`Erlang error: {{%Phoenix.Router.NoRouteError ...` for not-found requests

### ISSUE THREAD

**Issue by moxley** [honeybadger-io/honeybadger-elixir#193] opened 2018-12-28 00:51 UTC
As reported in this comment: https://github.com/honeybadger-io/honeybadger-elixir/issues/130#issuecomment-446118498. This is a separate issue from #130.

This same issue is causing any error that originates in a Plug app to be reported twice-- once the "normal" way, and again with the error wrapped in an Erlang error.

As a workaround, you can turn off the `use_logger` configuration:
```elixir
config :honeybadger,
  use_logger: false
```

Here's my analysis of the problem:

What is happening in a nutshell: The Honeybadger package is receiving the reported error event from Erlang's `:gen_event` system after the error is initially triggered and handled in the Plug pipeline.

Plug has a pluggable error handling system that Honeybadger uses to report errors from a Plug application. That system seems to be working correctly. Honeybadger receives the `NoRouteError` that way, and decides not to create a notification (thanks to #131).

However, after the error is handled by Honeybadger, `Plug.ErrorHandler` re-raises it (using `:erlang.raise/3`). It is then caught by `Phoenix.Endpoint.Cowboy2Handler.init/2`, re-raised (using `Kernel.exit/1`), then caught again by Cowboy's `cowboy_handler.erl`. From there, it is re-raised one more time (`:erlang.raise/3`), and I haven't followed where it's caught next, but probably somewhere inside Erlang. From there, the `:gen_event` application turns it into an event and publishes it. `Honeybadger.Logger.handle_event/2` picks up the event and turns it into a Honeybadger notification, which shows up as an error report starting with `Erlang error: {{%Phoenix.Router.NoRouteError{conn: %Plug.Conn{ ...`

So this question is: when Honeybadger is using the `:gen_event` system to detect errors, how is it supposed to know if an error originates from Plug or not (it should only be concerned with non-Plug errors in this case). Or, should it not receive Plug errors?

Honeybadger 0.10.3
Elixir 1.7.4
OTP 21
Phoenix 1.4.0
Plug 1.7.1
Plug Cowboy 2.0.0
Cowboy 2.6.1

**Comment by tielur** [comment] 2019-01-02 23:51
I'm getting this same error:

honeybadger 0.10.3
elixir 1.6.5
OTP 19
phoenix 1.4.0
plug 1.7.1
plug_cowboy 2.0.0
cowboy 2.6.0

**Comment by tielur** [comment] 2019-01-03 01:10
I'm curious as to why this is happening *now*. The reraising of an error from Plug.ErrorHandler has been there for years, also the gen_event handling inside of HoneyBadger.Logger has been there for over a year. 

I'm not sure why these are just now showing up in Honeybadger.

**Comment by moxley** [comment] 2019-01-03 01:20
@tielur: I'm curious too. I thought the OTP version made the difference, because SASL (which is referenced in the README) is no longer used in OTP 21. But you're on 19. 🤷‍♂️ 

We recently upgraded our dependencies-- including Honeybadger-- and this issue started happening around that time.

**Comment by tielur** [comment] 2019-01-04 20:47
So I *think* I found out more information a la: https://github.com/appsignal/appsignal-elixir/issues/417

**Comment by tielur** [comment] 2019-01-04 21:21
As a quick work around, if you don't need `plug_cowboy` 2.0+, you can downgrade to `{:plug_cowboy, "~> 1.0"}` in the short term.

**Comment by sorentwo** [comment] 2019-01-04 21:23
@tielur Thanks for the appsignal links, that is very helpful. I'm back from vacation and will look into fixes for this starting next week.

**Comment by sorentwo** [comment] 2019-06-01 22:25
This was essentially a duplicate of #130. We haven't had any new reports of this since 0.11 was released either. Closing this one out.

**Closed by sorentwo** 2019-06-01 22:25 UTC
Labels: bug
